import type { MethodologyId, MethodologyMetadata } from "./types";

export const METHODOLOGY_METADATA: Record<MethodologyId, MethodologyMetadata> = {
  pomodoro: {
    id: "pomodoro",
    name: "Pomodoro Technique",
    tagline: "25 minutes of focus. 5 minutes of rest. Repeat.",
    description: "Work in focused 25-minute intervals (Pomodoros) separated by short breaks. After 4 Pomodoros, take a longer break. Simple, effective, and the foundation of structured focus.",
    icon: "Timer",
    color: "#e03131",
    colorLight: "#ffe3e3",
    creator: "Francesco Cirillo",
    keyBenefit: "Eliminates procrastination by making focus manageable",
    idealFor: ["People who struggle to start tasks", "Those easily distracted", "Anyone who loses track of time"],
    videoDescription: "How the Pomodoro Technique turns 25 minutes into your most powerful productivity tool",
    onboardingHook: "Can't focus for long? You only need 25 minutes.",
  },
  gtd: {
    id: "gtd",
    name: "Getting Things Done",
    tagline: "Capture everything. Organize once. Trust your system.",
    description: "David Allen's complete productivity system: capture all commitments into an inbox, clarify next actions, organize by context, review weekly, and execute with confidence. Your mind becomes free to think, not remember.",
    icon: "Tray",
    color: "#2f9e44",
    colorLight: "#d3f9d8",
    creator: "David Allen",
    keyBenefit: "Eliminates mental overhead by externalizing all commitments",
    idealFor: ["People juggling many projects", "Those with racing minds", "Anyone who drops balls"],
    videoDescription: "Master the 5-step GTD workflow that Fortune 500 executives swear by",
    onboardingHook: "Too many things in your head? Get them ALL out.",
  },
  eisenhower: {
    id: "eisenhower",
    name: "Eisenhower Matrix",
    tagline: "What's important is seldom urgent. What's urgent is seldom important.",
    description: "Sort every task into four quadrants based on urgency and importance. Do urgent+important. Schedule important-not-urgent. Delegate urgent-not-important. Eliminate the rest. Focus on Q2 for strategic advantage.",
    icon: "GridFour",
    color: "#1971c2",
    colorLight: "#d0ebff",
    creator: "Dwight D. Eisenhower",
    keyBenefit: "Prevents urgency from hijacking what actually matters",
    idealFor: ["Decision makers", "People who feel busy but unproductive", "Those who say yes to everything"],
    videoDescription: "The decision matrix that helped run a country — and can run your day",
    onboardingHook: "Busy all day but nothing important gets done?",
  },
  time_blocking: {
    id: "time_blocking",
    name: "Time Blocking",
    tagline: "If it's not on your calendar, it doesn't get done.",
    description: "Assign every hour of your day to specific tasks or categories. No more wondering what to work on next. Your calendar becomes your productivity operating system. Guard your blocks like meetings with yourself.",
    icon: "CalendarBlank",
    color: "#7048e8",
    colorLight: "#e5dbff",
    creator: "Cal Newport / Elon Musk",
    keyBenefit: "Eliminates decision fatigue by pre-deciding your day",
    idealFor: ["People with flexible schedules", "Those who waste time deciding what to do", "Remote workers"],
    videoDescription: "How billionaires structure every hour — and how you can too",
    onboardingHook: "Where did the day go? Time blocking tells you.",
  },
  pareto: {
    id: "pareto",
    name: "80/20 Rule (Pareto)",
    tagline: "80% of results come from 20% of effort. Find your 20%.",
    description: "Identify the vital few activities that generate the majority of your results. Double down on high-impact work. Eliminate or minimize everything else. Work smarter by focusing on leverage, not effort.",
    icon: "ChartBar",
    color: "#e8590c",
    colorLight: "#ffe8cc",
    creator: "Vilfredo Pareto",
    keyBenefit: "Maximizes output per unit of time invested",
    idealFor: ["Entrepreneurs", "People who work hard but spin their wheels", "Anyone seeking leverage"],
    videoDescription: "Find the 20% of your work that creates 80% of your value",
    onboardingHook: "Working hard but not getting proportional results?",
  },
  deep_work: {
    id: "deep_work",
    name: "Deep Work",
    tagline: "Distraction-free focus on cognitively demanding tasks.",
    description: "Extended periods (60-120 min) of uninterrupted, cognitively demanding work. Eliminate all distractions. Train your brain to sustain intense concentration. This is where breakthroughs happen.",
    icon: "Brain",
    color: "#0c8599",
    colorLight: "#c3fae8",
    creator: "Cal Newport",
    keyBenefit: "Produces high-quality work that shallow work can't match",
    idealFor: ["Knowledge workers", "Creators and writers", "Engineers and researchers"],
    videoDescription: "The neuroscience of deep focus and how to train your brain for it",
    onboardingHook: "Constant notifications destroying your best work?",
  },
  eat_the_frog: {
    id: "eat_the_frog",
    name: "Eat The Frog",
    tagline: "Do the hardest thing first. Everything else is easy.",
    description: "Identify the most challenging, most important task of your day — your 'frog' — and do it FIRST. Before email. Before meetings. Before anything comfortable. This builds discipline and ensures your highest-value work gets done.",
    icon: "FrogFace",
    color: "#66a80f",
    colorLight: "#d8f5a2",
    creator: "Brian Tracy / Mark Twain",
    keyBenefit: "Builds discipline and guarantees your hardest task gets done",
    idealFor: ["Procrastinators", "People who save hard tasks for 'later'", "Those with low morning motivation"],
    videoDescription: "Why eating the frog first thing changes your entire day",
    onboardingHook: "Always putting off the hard stuff until 'later'?",
  },
  two_minute: {
    id: "two_minute",
    name: "Two-Minute Rule",
    tagline: "If it takes less than two minutes, do it now.",
    description: "Any task that takes under 2 minutes should be done immediately rather than tracked, scheduled, or deferred. The overhead of managing it exceeds the time to complete it. Keep your system clean.",
    icon: "Lightning",
    color: "#f08c00",
    colorLight: "#fff3bf",
    creator: "David Allen",
    keyBenefit: "Prevents small tasks from piling up and creating overwhelm",
    idealFor: ["People with overflowing to-do lists", "Those who overthink small tasks", "Email heavy workers"],
    videoDescription: "The deceptively simple rule that eliminates task pile-up",
    onboardingHook: "Tiny tasks piling up into a mountain of overwhelm?",
  },
  batch: {
    id: "batch",
    name: "Batch Processing",
    tagline: "Group similar tasks. Eliminate context switching.",
    description: "Instead of switching between different types of tasks throughout the day, group similar tasks into dedicated sessions. Emails in one block. Calls in another. Reports together. Reduce the cognitive cost of context switching.",
    icon: "SquaresFour",
    color: "#9c36b5",
    colorLight: "#f3d9fa",
    creator: "Various",
    keyBenefit: "Reduces context-switching overhead by 40%+",
    idealFor: ["People who multitask", "Those with many similar recurring tasks", "Anyone who feels scattered"],
    videoDescription: "How batch processing saves hours by eliminating the hidden cost of switching",
    onboardingHook: "Jumping between tasks all day and finishing nothing?",
  },
  time_audit: {
    id: "time_audit",
    name: "Time Audit",
    tagline: "You can't manage what you don't measure.",
    description: "Track exactly how you spend every hour for at least 2 weeks. Compare perception vs reality. Discover hidden time sinks. Use data to make informed decisions about where your time goes. What gets measured gets managed.",
    icon: "ClockClockwise",
    color: "#495057",
    colorLight: "#e9ecef",
    creator: "Peter Drucker",
    keyBenefit: "Reveals the truth about where your time actually goes",
    idealFor: ["People who feel time-poor", "Those who want data-driven improvement", "Anyone who says 'where did the day go?'"],
    videoDescription: "The eye-opening exercise that reveals your true time allocation",
    onboardingHook: "Think you know where your time goes? The data will surprise you.",
  },
};

export const METHODOLOGY_PROGRESSION: Record<MethodologyId, MethodologyId[]> = {
  pomodoro: ["time_blocking", "deep_work", "batch"],
  gtd: ["two_minute", "eisenhower", "batch"],
  eisenhower: ["eat_the_frog", "pareto", "time_audit"],
  time_blocking: ["pomodoro", "deep_work", "batch"],
  pareto: ["eisenhower", "time_audit", "eat_the_frog"],
  deep_work: ["time_blocking", "eat_the_frog", "pomodoro"],
  eat_the_frog: ["eisenhower", "pomodoro", "deep_work"],
  two_minute: ["gtd", "batch", "eisenhower"],
  batch: ["time_blocking", "pomodoro", "two_minute"],
  time_audit: ["pareto", "time_blocking", "eisenhower"],
};
