export const ROUTES = {
  home: "/",
  signIn: "/sign-in",
  signUp: "/sign-up",
  onboarding: "/onboarding",
  onboardingMethodology: (slug: string) => `/onboarding/${slug}` as const,
  dashboard: "/dashboard",
  techniques: {
    pomodoro: "/techniques/pomodoro",
    pomodoroHistory: "/techniques/pomodoro/history",
    pomodoroSettings: "/techniques/pomodoro/settings",
    eisenhower: "/techniques/eisenhower",
    timeBlocking: "/techniques/time-blocking",
    twoMinute: "/techniques/two-minute",
    gtd: "/techniques/gtd",
    gtdInbox: "/techniques/gtd/inbox",
    gtdProjects: "/techniques/gtd/projects",
    gtdContexts: "/techniques/gtd/contexts",
    gtdWaiting: "/techniques/gtd/waiting",
    gtdReview: "/techniques/gtd/review",
    deepWork: "/techniques/deep-work",
    eatTheFrog: "/techniques/eat-the-frog",
    pareto: "/techniques/pareto",
    batch: "/techniques/batch",
    timeAudit: "/techniques/time-audit",
    timeAuditReports: "/techniques/time-audit/reports",
  },
  coach: "/coach",
  coachInsights: "/coach/insights",
  analytics: "/analytics",
  analyticsProductivity: "/analytics/productivity",
  analyticsReports: "/analytics/reports",
  settings: "/settings",
  settingsNotifications: "/settings/notifications",
  settingsIntegrations: "/settings/integrations",
  settingsBilling: "/settings/billing",
  admin: "/admin",
  adminUsers: "/admin/users",
  adminAuditLog: "/admin/audit-log",
} as const;

export const PUBLIC_ROUTES = [
  "/",
  "/pricing",
  "/features",
  "/sign-in(.*)",
  "/sign-up(.*)",
  "/api/webhooks(.*)",
];

export const AUTH_ROUTES = ["/sign-in(.*)", "/sign-up(.*)"];
